# Generated by Django 6.0.3 on 2026-04-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_qa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
